/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarefasIndexRouteImport } from './routes/tarefas/index'
import { Route as FinancasIndexRouteImport } from './routes/financas/index'
import { Route as TarefasTodasRouteImport } from './routes/tarefas/todas'
import { Route as TarefasProximosRouteImport } from './routes/tarefas/proximos'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as TarefasProjetosIdRouteImport } from './routes/tarefas/projetos.$id'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasIndexRoute = TarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasIndexRoute = FinancasIndexRouteImport.update({
  id: '/financas/',
  path: '/financas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasTodasRoute = TarefasTodasRouteImport.update({
  id: '/tarefas/todas',
  path: '/tarefas/todas',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasProximosRoute = TarefasProximosRouteImport.update({
  id: '/tarefas/proximos',
  path: '/tarefas/proximos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasProjetosIdRoute = TarefasProjetosIdRouteImport.update({
  id: '/tarefas/projetos/$id',
  path: '/tarefas/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/purchases': typeof PurchasesRoute
  '/tasks': typeof TasksRoute
  '/upcoming': typeof UpcomingRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tarefas/proximos': typeof TarefasProximosRoute
  '/tarefas/todas': typeof TarefasTodasRoute
  '/financas/': typeof FinancasIndexRoute
  '/tarefas/': typeof TarefasIndexRoute
  '/tarefas/projetos/$id': typeof TarefasProjetosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/purchases': typeof PurchasesRoute
  '/tasks': typeof TasksRoute
  '/upcoming': typeof UpcomingRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tarefas/proximos': typeof TarefasProximosRoute
  '/tarefas/todas': typeof TarefasTodasRoute
  '/financas': typeof FinancasIndexRoute
  '/tarefas': typeof TarefasIndexRoute
  '/tarefas/projetos/$id': typeof TarefasProjetosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/purchases': typeof PurchasesRoute
  '/tasks': typeof TasksRoute
  '/upcoming': typeof UpcomingRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tarefas/proximos': typeof TarefasProximosRoute
  '/tarefas/todas': typeof TarefasTodasRoute
  '/financas/': typeof FinancasIndexRoute
  '/tarefas/': typeof TarefasIndexRoute
  '/tarefas/projetos/$id': typeof TarefasProjetosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/notes'
    | '/purchases'
    | '/tasks'
    | '/upcoming'
    | '/projects/$id'
    | '/tarefas/proximos'
    | '/tarefas/todas'
    | '/financas/'
    | '/tarefas/'
    | '/tarefas/projetos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/notes'
    | '/purchases'
    | '/tasks'
    | '/upcoming'
    | '/projects/$id'
    | '/tarefas/proximos'
    | '/tarefas/todas'
    | '/financas'
    | '/tarefas'
    | '/tarefas/projetos/$id'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/dashboard'
    | '/notes'
    | '/purchases'
    | '/tasks'
    | '/upcoming'
    | '/projects/$id'
    | '/tarefas/proximos'
    | '/tarefas/todas'
    | '/financas/'
    | '/tarefas/'
    | '/tarefas/projetos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  DashboardRoute: typeof DashboardRoute
  NotesRoute: typeof NotesRoute
  PurchasesRoute: typeof PurchasesRoute
  TasksRoute: typeof TasksRoute
  UpcomingRoute: typeof UpcomingRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  TarefasProximosRoute: typeof TarefasProximosRoute
  TarefasTodasRoute: typeof TarefasTodasRoute
  FinancasIndexRoute: typeof FinancasIndexRoute
  TarefasIndexRoute: typeof TarefasIndexRoute
  TarefasProjetosIdRoute: typeof TarefasProjetosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/': {
      id: '/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof TarefasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas/': {
      id: '/financas/'
      path: '/financas'
      fullPath: '/financas/'
      preLoaderRoute: typeof FinancasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/todas': {
      id: '/tarefas/todas'
      path: '/tarefas/todas'
      fullPath: '/tarefas/todas'
      preLoaderRoute: typeof TarefasTodasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/proximos': {
      id: '/tarefas/proximos'
      path: '/tarefas/proximos'
      fullPath: '/tarefas/proximos'
      preLoaderRoute: typeof TarefasProximosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas/projetos/$id': {
      id: '/tarefas/projetos/$id'
      path: '/tarefas/projetos/$id'
      fullPath: '/tarefas/projetos/$id'
      preLoaderRoute: typeof TarefasProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  DashboardRoute: DashboardRoute,
  NotesRoute: NotesRoute,
  PurchasesRoute: PurchasesRoute,
  TasksRoute: TasksRoute,
  UpcomingRoute: UpcomingRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  TarefasProximosRoute: TarefasProximosRoute,
  TarefasTodasRoute: TarefasTodasRoute,
  FinancasIndexRoute: FinancasIndexRoute,
  TarefasIndexRoute: TarefasIndexRoute,
  TarefasProjetosIdRoute: TarefasProjetosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
